# Generated by Django 5.2.12 on 2026-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0090_backfill_bindingmapping_v2_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("delete", "Delete"),
                    ("add", "Add"),
                    ("edit", "Edit"),
                    ("create", "Create"),
                    ("remove", "Remove"),
                    ("read", "Read"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("role", "Role"),
                    ("role_v2", "V2 Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("workspace", "Workspace"),
                    ("role_binding", "Role Binding"),
                    ("principal", "Principal"),
                ],
                max_length=32,
            ),
        ),
    ]
