# Generated by Django 6.0.8 on 2026-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0094_tenantmapping_v2_opted_in_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("group_v2", "V2 Group"),
                    ("role", "Role"),
                    ("role_v2", "V2 Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("workspace", "Workspace"),
                    ("role_binding", "Role Binding"),
                ],
                max_length=32,
            ),
        ),
    ]
